FROM python:3.8

WORKDIR /usr/src/app
COPY . ./

ARG ENTITY_EMBEDDING_URL
ARG RELATION_EMBEDDING_URL
ARG ENTITY_MAPPING_URL
ARG RELATION_MAPPING_URL

ARG ENTITY_EMBEDDING_PATH=/usr/src/app/heritageconnector_RotatE_entity.npy
ARG ENTITY_MAPPING_PATH=/usr/src/app/entities.tsv
ARG RELATION_EMBEDDING_PATH=/usr/src/app/heritageconnector_RotatE_relation.npy
ARG RELATION_MAPPING_PATH=/usr/src/app/relations.tsv

RUN echo $ENTITY_EMBEDDING_URL
RUN echo $RELATION_EMBEDDING_URL
RUN echo $ENTITY_MAPPING_URL
RUN echo $RELATION_MAPPING_URL

RUN curl -L $ENTITY_EMBEDDING_URL -o $ENTITY_EMBEDDING_PATH
RUN curl -L $RELATION_EMBEDDING_URL -o $RELATION_EMBEDDING_PATH
RUN curl -L $ENTITY_MAPPING_URL -o $ENTITY_MAPPING_PATH
RUN curl -L $RELATION_MAPPING_URL -o $RELATION_MAPPING_PATH

ENV ENTITY_EMBEDDING_PATH $ENTITY_EMBEDDING_PATH
ENV ENTITY_MAPPING_PATH $ENTITY_MAPPING_PATH
ENV RELATION_EMBEDDING_PATH $RELATION_EMBEDDING_PATH
ENV RELATION_MAPPING_PATH $RELATION_MAPPING_PATH

RUN pip install --upgrade pip
RUN pip install -r requirements_min.txt

CMD python -m src.api -p 8020